### ISSUE TITLE
想问一下后期会提供mmdet的模型源码么

### ISSUE THREAD

**Issue by njauwhr** [lingtengqiu/ETHSeg#1]
1.是否会提供源码
2.给的下载链接，下载的数据集只有5000张左右，和论文中的好像不太一致，可否再给一个下载数据集的地址
谢谢

**Comment by lingtengqiu** [comment]
由于和公司有部分合作的原因，code 这段时间可能不会放，数据的话我们这边在check 一下

**Comment by njauwhr** [comment]
好的，保持关注，希望早日可以提供源码，十分感谢

**Comment by lingtengqiu** [comment]
In total, our WIXray contains 5, 038 X-ray images and 30, 881 waste instances covering 12 common waste categories; 我想应该和我们paper 的论述是一致的；数据集就是5000张左右。
